[playlist]
numberofentries=5
File1=http://208.101.41.235:43944
Title1=(#1 - 85/200) k a w a i i - r a d i o | sr1 http://kawaii-radio.net
Length1=-1
File2=http://91.121.88.118:9000
Title2=(#2 - 44/100) k a w a i i - r a d i o | sr1 http://kawaii-radio.net
Length2=-1
File3=http://83.170.83.133:8092
Title3=(#3 - 59/128) k a w a i i - r a d i o | sr1 http://kawaii-radio.net
Length3=-1
File4=http://91.121.5.99:9000
Title4=(#4 - 188/300) k a w a i i - r a d i o | sr1 http://kawaii-radio.net
Length4=-1
File5=http://66.171.242.32:9000
Title5=(#5 - 111/150) k a w a i i - r a d i o | sr1 http://kawaii-radio.net
Length5=-1
Version=2
