/*                                                                           */
/*       ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป        */
/*       บ BC - Background Carousel           Tony Bearman 10/09/95 บ        */
/*       บ                                            Version 1.00  บ        */
/*       บ Usage  :  BC [options]                                   บ        */
/*       บ Purpose:  Change desktop background automatically        บ        */
/*       บ Options:  (case insensitive)                             บ        */
/*       บ           /d - delete all current settings               บ        */
/*       บ           /l - list current settings                     บ        */
/*       บ           /? - help                                      บ        */
/*       วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤถ        */
/*       บ  Free for personal use. The author may be contacted at   บ        */
/*       บ                                                          บ        */
/*       บ              Fidonet    1:153/920                        บ        */
/*       บ              Internet   tony@ship.net                    บ        */
/*       บ              Paper      Box 34128                        บ        */
/*       บ                         5790 - 175th Street              บ        */
/*       บ                         Surrey BC, Canada                บ        */
/*       บ                         V3S 8C4                          บ        */
/*       บ                                                          บ        */
/*       บ   Copyright (C) Tony Bearman, 1995. All rights reserved. บ        */
/*       ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ        */
/*                                                                           */
/* compiled on 10/09/95 at 08:16:49 with REXXCC V1.01 (c) Bernd Schemmer 1994 */  
