[playlist]
numberofentries=3
File1=http://87.118.64.199:80
Title1=(#1 - 156/250) Radio VHR - Schlager, Volksmusik, Deutsch Pop, Deutsch Rock
Length1=-1
File2=http://87.118.106.215:8010
Title2=(#2 - 318/500) Radio VHR - Schlager, Volksmusik, Deutsch Pop, Deutsch Rock
Length2=-1
File3=http://87.118.64.199:8000
Title3=(#3 - 148/150) Radio VHR - Schlager, Volksmusik, Deutsch Pop, Deutsch Rock
Length3=-1
Version=2
