
/* Extended help */

#define IDXH_BROWSE         405
#define IDXH_KEYS           406

/* Help for main menu choices */

#define IDMH_FILE           407
#define IDMH_OPEN           408
#define IDMH_EXIT           409

#define IDMH_EDIT           410
#define IDMH_COPY           411
#define IDMH_FIND           412
#define IDMH_SELECTALL      413

#define IDMH_OPTIONS        414
#define IDMH_SETFONT        415
#define IDMH_SETCOLORS      416
#define IDMH_WORDWRAP       417

#define IDMH_HELP           418
#define IDMH_HELPFORHELP    419
#define IDMH_HELPFORBROWSE  420
#define IDMH_KEYS           421
#define IDMH_INDEX          422
#define IDMH_ABOUT          423

